(function(d){var v,k,m,l,n,p,q,r,s,w,t;v=document.namespaces;k=!!document.createElement("canvas").getContext;d.mynamespace={in_focus:null};if(!k&&!v)d.fn.maphilight=function(){return this};else{if(k){r=function(b){return Math.max(0,Math.min(parseInt(b,16),255))};s=function(b,d){return"rgba("+r(b.substr(0,2))+","+r(b.substr(2,2))+","+r(b.substr(4,2))+","+d+")"};m=function(b){b=d('<canvas style="width:'+b.width+"px;height:"+b.height+'px;"></canvas>').get(0);b.getContext("2d").clearRect(0,0,b.width,
b.height);return b};var u=function(b,d,a,c,e){c=c||0;e=e||0;b.beginPath();if("rect"==d)b.rect(a[0]+c,a[1]+e,a[2]-a[0],a[3]-a[1]);else if("poly"==d){b.moveTo(a[0]+c,a[1]+e);for(i=2;i<a.length;i+=2)b.lineTo(a[i]+c,a[i+1]+e)}else"circ"==d&&b.arc(a[0]+c,a[1]+e,a[2],0,2*Math.PI,!1);b.closePath()};l=function(b,j,a,c){var e=b.getContext("2d");if(c.shadow){e.save();"inside"==c.shadowPosition&&(u(e,j,a),e.clip());var g=100*b.width,f=100*b.height;u(e,j,a,g,f);e.shadowOffsetX=c.shadowX-g;e.shadowOffsetY=c.shadowY-
f;e.shadowBlur=c.shadowRadius;e.shadowColor=s(c.shadowColor,c.shadowOpacity);(g=c.shadowFrom)||(g="outside"==c.shadowPosition?"fill":"stroke");"stroke"==g?(e.strokeStyle="rgba(0,0,0,1)",e.stroke()):"fill"==g&&(e.fillStyle="rgba(0,0,0,1)",e.fill());e.restore();"outside"==c.shadowPosition&&(e.save(),u(e,j,a),e.globalCompositeOperation="destination-out",e.fillStyle="rgba(0,0,0,1);",e.fill(),e.restore())}e.save();u(e,j,a);c.fill&&(e.fillStyle=s(c.fillColor,c.fillOpacity),e.fill());c.stroke&&(e.strokeStyle=
s(c.strokeColor,c.strokeOpacity),e.lineWidth=c.strokeWidth,e.stroke());e.restore();c.fade&&d(b).css("opacity",0).animate({opacity:1},100)};n=function(b){b.getContext("2d").clearRect(0,0,b.width,b.height);d.mynamespace.in_focus&&(document.getElementById(d.mynamespace.in_focus).setAttribute("style","background-color: white; border:0"),d.mynamespace.in_focus=null)}}else m=function(b){return d('<var style="zoom:1;overflow:hidden;display:block;width:'+b.width+"px;height:"+b.height+'px;"></var>').get(0)},
l=function(b,j,a,c,e){var g,f,h;g='<v:fill color="#'+c.fillColor+'" opacity="'+(c.fill?c.fillOpacity:0)+'" />';f=c.stroke?'strokeweight="'+c.strokeWidth+'" stroked="t" strokecolor="#'+c.strokeColor+'"':'stroked="f"';c='<v:stroke opacity="'+c.strokeOpacity+'"/>';"rect"==j?h=d('<v:rect name="'+e+'" filled="t" '+f+' style="zoom:1;margin:0;padding:0;display:block;position:absolute;left:'+a[0]+"px;top:"+a[1]+"px;width:"+(a[2]-a[0])+"px;height:"+(a[3]-a[1])+'px;"></v:rect>'):"poly"==j?h=d('<v:shape name="'+
e+'" filled="t" '+f+' coordorigin="0,0" coordsize="'+b.width+","+b.height+'" path="m '+a[0]+","+a[1]+" l "+a.join(",")+' x e" style="zoom:1;margin:0;padding:0;display:block;position:absolute;top:0px;left:0px;width:'+b.width+"px;height:"+b.height+'px;"></v:shape>'):"circ"==j&&(h=d('<v:oval name="'+e+'" filled="t" '+f+' style="zoom:1;margin:0;padding:0;display:block;position:absolute;left:'+(a[0]-a[2])+"px;top:"+(a[1]-a[2])+"px;width:"+2*a[2]+"px;height:"+2*a[2]+'px;"></v:oval>'));h.get(0).innerHTML=
g+c;d(b).append(h)},n=function(b){d(b).find("[name=highlighted]").remove()};p=function(b){var d,a=b.getAttribute("coords").split(",");for(d=0;d<a.length;d++)a[d]=parseFloat(a[d]);return[b.getAttribute("shape").toLowerCase().substr(0,4),a]};t=function(b,j){var a=d(b);return d.extend({},j,d.metadata?a.metadata():!1,a.data("maphilight"))};w=function(b){return!b.complete||"undefined"!=typeof b.naturalWidth&&0===b.naturalWidth?!1:!0};q={position:"absolute",left:0,top:0,padding:0,border:0};var x=!1;d.fn.maphilight=
function(b){b=d.extend({},d.fn.maphilight.defaults,b);if(!k&&d.browser.msie&&!x){document.namespaces.add("v","urn:schemas-microsoft-com:vml");var j=document.createStyleSheet();d.each("shape rect oval circ fill stroke imagedata group textbox".split(" "),function(){j.addRule("v\\:"+this,"behavior: url(#default#VML); antialias:true")});x=!0}return this.each(function(){var a,c,e,g,f,h;a=d(this);if(!w(this))return window.setTimeout(function(){a.maphilight(b)},200);e=d.extend({},b,d.metadata?a.metadata():
!1,a.data("maphilight"));c=a.get(0).getAttribute("usemap");g=d('map[name="'+c.substr(1)+'"]');a.is('img,input[type="image"]')&&(c&&0<g.size())&&(a.hasClass("maphilighted")&&(c=a.parent(),a.insertBefore(c),c.remove(),d(g).unbind(".maphilight").find("area[coords]").unbind(".maphilight")),c=d("<div></div>").css({display:"block",background:'url("'+this.src+'")',"background-size":this.width,"background-repeat":"no-repeat",position:"relative",padding:0,width:this.width,height:this.height}),e.wrapClass&&
(!0===e.wrapClass?c.addClass(d(this).attr("class")):c.addClass(e.wrapClass)),a.before(c).css("opacity",0).css(q).remove(),d.browser.msie&&a.css("filter","Alpha(opacity=0)"),c.append(a),f=m(this),d(f).css(q),f.height=this.height,f.width=this.width,c=function(){var a,b;b=t(this,e);if(!b.neverOn&&!b.alwaysOn){a=p(this);l(f,a[0],a[1],b,"highlighted");if(a=d(this).attr("href")){a=a.substr(1);var c=document.getElementById(a);null!=c&&(c.setAttribute("style","background-color: rgba(255,0,0,0.4)"),d.mynamespace.in_focus=
a)}if(b.groupBy){var h=this;(/^[a-zA-Z][\-a-zA-Z]+$/.test(b.groupBy)?g.find("area["+b.groupBy+'="'+d(this).attr(b.groupBy)+'"]'):g.find(b.groupBy)).each(function(){if(this!=h){var a=t(this,e);if(!a.neverOn&&!a.alwaysOn){var b=p(this);l(f,b[0],b[1],a,"highlighted")}}})}k||d(f).append("<v:rect></v:rect>")}},d(g).bind("alwaysOn.maphilight",function(){h&&n(h);k||d(f).empty();d(g).find("area[coords]").each(function(){var b,c;c=t(this,e);c.alwaysOn&&(!h&&k&&(h=m(a[0]),d(h).css(q),h.width=a[0].width,h.height=
a[0].height,a.before(h)),c.fade=c.alwaysOnFade,b=p(this),k?l(h,b[0],b[1],c,""):l(f,b[0],b[1],c,""))})}),d(g).trigger("alwaysOn.maphilight").find("area[coords]").bind("mouseover.maphilight",c).bind("mouseout.maphilight",function(){n(f)}),a.before(f),a.addClass("maphilighted"))})};d.fn.maphilight.defaults={fill:!0,fillColor:"000000",fillOpacity:0.2,stroke:!0,strokeColor:"ff0000",strokeOpacity:1,strokeWidth:1,fade:!0,alwaysOn:!1,neverOn:!1,groupBy:!1,wrapClass:!0,shadow:!1,shadowX:0,shadowY:0,shadowRadius:6,
shadowColor:"000000",shadowOpacity:0.8,shadowPosition:"outside",shadowFrom:!1}}})(jQuery);
