(function(d){var v,k,m,l,n,p,q,r,s,w,t;v=document.namespaces;k=!!document.createElement("canvas").getContext;if(!k&&!v)d.fn.maphilight=function(){return this};else{if(k){r=function(a){return Math.max(0,Math.min(parseInt(a,16),255))};s=function(a,d){return"rgba("+r(a.substr(0,2))+","+r(a.substr(2,2))+","+r(a.substr(4,2))+","+d+")"};m=function(a){a=d('<canvas style="width:'+a.width+"px;height:"+a.height+'px;"></canvas>').get(0);a.getContext("2d").clearRect(0,0,a.width,a.height);return a};var u=function(a,
d,b,c,e){c=c||0;e=e||0;a.beginPath();if("rect"==d)a.rect(b[0]+c,b[1]+e,b[2]-b[0],b[3]-b[1]);else if("poly"==d){a.moveTo(b[0]+c,b[1]+e);for(i=2;i<b.length;i+=2)a.lineTo(b[i]+c,b[i+1]+e)}else"circ"==d&&a.arc(b[0]+c,b[1]+e,b[2],0,2*Math.PI,!1);a.closePath()};l=function(a,j,b,c){var e=a.getContext("2d");if(c.shadow){e.save();"inside"==c.shadowPosition&&(u(e,j,b),e.clip());var g=100*a.width,f=100*a.height;u(e,j,b,g,f);e.shadowOffsetX=c.shadowX-g;e.shadowOffsetY=c.shadowY-f;e.shadowBlur=c.shadowRadius;
e.shadowColor=s(c.shadowColor,c.shadowOpacity);(g=c.shadowFrom)||(g="outside"==c.shadowPosition?"fill":"stroke");"stroke"==g?(e.strokeStyle="rgba(0,0,0,1)",e.stroke()):"fill"==g&&(e.fillStyle="rgba(0,0,0,1)",e.fill());e.restore();"outside"==c.shadowPosition&&(e.save(),u(e,j,b),e.globalCompositeOperation="destination-out",e.fillStyle="rgba(0,0,0,1);",e.fill(),e.restore())}e.save();u(e,j,b);c.fill&&(e.fillStyle=s(c.fillColor,c.fillOpacity),e.fill());c.stroke&&(e.strokeStyle=s(c.strokeColor,c.strokeOpacity),
e.lineWidth=c.strokeWidth,e.stroke());e.restore();c.fade&&d(a).css("opacity",0).animate({opacity:1},100)};n=function(a){a.getContext("2d").clearRect(0,0,a.width,a.height)}}else m=function(a){return d('<var style="zoom:1;overflow:hidden;display:block;width:'+a.width+"px;height:"+a.height+'px;"></var>').get(0)},l=function(a,j,b,c,e){var g,f,h;g='<v:fill color="#'+c.fillColor+'" opacity="'+(c.fill?c.fillOpacity:0)+'" />';f=c.stroke?'strokeweight="'+c.strokeWidth+'" stroked="t" strokecolor="#'+c.strokeColor+
'"':'stroked="f"';c='<v:stroke opacity="'+c.strokeOpacity+'"/>';"rect"==j?h=d('<v:rect name="'+e+'" filled="t" '+f+' style="zoom:1;margin:0;padding:0;display:block;position:absolute;left:'+b[0]+"px;top:"+b[1]+"px;width:"+(b[2]-b[0])+"px;height:"+(b[3]-b[1])+'px;"></v:rect>'):"poly"==j?h=d('<v:shape name="'+e+'" filled="t" '+f+' coordorigin="0,0" coordsize="'+a.width+","+a.height+'" path="m '+b[0]+","+b[1]+" l "+b.join(",")+' x e" style="zoom:1;margin:0;padding:0;display:block;position:absolute;top:0px;left:0px;width:'+
a.width+"px;height:"+a.height+'px;"></v:shape>'):"circ"==j&&(h=d('<v:oval name="'+e+'" filled="t" '+f+' style="zoom:1;margin:0;padding:0;display:block;position:absolute;left:'+(b[0]-b[2])+"px;top:"+(b[1]-b[2])+"px;width:"+2*b[2]+"px;height:"+2*b[2]+'px;"></v:oval>'));h.get(0).innerHTML=g+c;d(a).append(h)},n=function(a){d(a).find("[name=highlighted]").remove()};p=function(a){var d,b=a.getAttribute("coords").split(",");for(d=0;d<b.length;d++)b[d]=parseFloat(b[d]);return[a.getAttribute("shape").toLowerCase().substr(0,
4),b]};t=function(a,j){var b=d(a);return d.extend({},j,d.metadata?b.metadata():!1,b.data("maphilight"))};w=function(a){return!a.complete||"undefined"!=typeof a.naturalWidth&&0===a.naturalWidth?!1:!0};q={position:"absolute",left:0,top:0,padding:0,border:0};var x=!1;d.fn.maphilight=function(a){a=d.extend({},d.fn.maphilight.defaults,a);if(!k&&d.browser.msie&&!x){document.namespaces.add("v","urn:schemas-microsoft-com:vml");var j=document.createStyleSheet();d.each("shape rect oval circ fill stroke imagedata group textbox".split(" "),
function(){j.addRule("v\\:"+this,"behavior: url(#default#VML); antialias:true")});x=!0}return this.each(function(){var b,c,e,g,f,h;b=d(this);if(!w(this))return window.setTimeout(function(){b.maphilight(a)},200);e=d.extend({},a,d.metadata?b.metadata():!1,b.data("maphilight"));c=b.get(0).getAttribute("usemap");g=d('map[name="'+c.substr(1)+'"]');b.is('img,input[type="image"]')&&(c&&0<g.size())&&(b.hasClass("maphilighted")&&(c=b.parent(),b.insertBefore(c),c.remove(),d(g).unbind(".maphilight").find("area[coords]").unbind(".maphilight")),
c=d("<div></div>").css({display:"block",background:'url("'+this.src+'")',"background-size":this.width,"background-repeat":"no-repeat",position:"relative",padding:0,width:this.width,height:this.height}),e.wrapClass&&(!0===e.wrapClass?c.addClass(d(this).attr("class")):c.addClass(e.wrapClass)),b.before(c).css("opacity",0).css(q).remove(),d.browser.msie&&b.css("filter","Alpha(opacity=0)"),c.append(b),f=m(this),d(f).css(q),f.height=this.height,f.width=this.width,c=function(){var b,a;a=t(this,e);if(!a.neverOn&&
!a.alwaysOn){b=p(this);l(f,b[0],b[1],a,"highlighted");if(a.groupBy){var c=this;(/^[a-zA-Z][\-a-zA-Z]+$/.test(a.groupBy)?g.find("area["+a.groupBy+'="'+d(this).attr(a.groupBy)+'"]'):g.find(a.groupBy)).each(function(){if(this!=c){var b=t(this,e);if(!b.neverOn&&!b.alwaysOn){var a=p(this);l(f,a[0],a[1],b,"highlighted")}}})}k||d(f).append("<v:rect></v:rect>")}},d(g).bind("alwaysOn.maphilight",function(){h&&n(h);k||d(f).empty();d(g).find("area[coords]").each(function(){var a,c;c=t(this,e);c.alwaysOn&&(!h&&
k&&(h=m(b[0]),d(h).css(q),h.width=b[0].width,h.height=b[0].height,b.before(h)),c.fade=c.alwaysOnFade,a=p(this),k?l(h,a[0],a[1],c,""):l(f,a[0],a[1],c,""))})}),d(g).trigger("alwaysOn.maphilight").find("area[coords]").bind("mouseover.maphilight",c).bind("mouseout.maphilight",function(){n(f)}),b.before(f),b.addClass("maphilighted"))})};d.fn.maphilight.defaults={fill:!0,fillColor:"000000",fillOpacity:0.2,stroke:!0,strokeColor:"ff0000",strokeOpacity:1,strokeWidth:1,fade:!0,alwaysOn:!1,neverOn:!1,groupBy:!1,
wrapClass:!0,shadow:!1,shadowX:0,shadowY:0,shadowRadius:6,shadowColor:"000000",shadowOpacity:0.8,shadowPosition:"outside",shadowFrom:!1}}})(jQuery);
