(function(a){var j=!!document.createElement("canvas").getContext;if(j){var m=function(d){return Math.max(0,Math.min(parseInt(d,16),255))},n=function(d,b){return"rgba("+m(d.substr(0,2))+","+m(d.substr(2,2))+","+m(d.substr(4,2))+","+b+")"},p=function(d){var b=document.createElement("canvas");b.width=d.width;b.height=d.height;null==d.previousSibling?d.parentNode.insertBefore(b,d):d.parentNode.replaceChild(b,d.previousSibling);alert("create_canvas: c.width="+b.width);b.getContext("2d").clearRect(0,0,
b.width,b.height);return b},k=function(d,b,a,c,e){c=c||0;e=e||0;d.beginPath();if("rect"==b)d.rect(a[0]+c,a[1]+e,a[2]-a[0],a[3]-a[1]);else if("poly"==b){d.moveTo(a[0]+c,a[1]+e);for(i=2;i<a.length;i+=2)d.lineTo(a[i]+c,a[i+1]+e)}else"circ"==b&&d.arc(a[0]+c,a[1]+e,a[2],0,2*Math.PI,!1);d.closePath()},l=function(d,b,f,c){var e=d.getContext("2d");if(c.shadow){e.save();"inside"==c.shadowPosition&&(k(e,b,f),e.clip());var g=100*d.width,h=100*d.height;k(e,b,f,g,h);e.shadowOffsetX=c.shadowX-g;e.shadowOffsetY=
c.shadowY-h;e.shadowBlur=c.shadowRadius;e.shadowColor=n(c.shadowColor,c.shadowOpacity);(g=c.shadowFrom)||(g="outside"==c.shadowPosition?"fill":"stroke");"stroke"==g?(e.strokeStyle="rgba(0,0,0,1)",e.stroke()):"fill"==g&&(e.fillStyle="rgba(0,0,0,1)",e.fill());e.restore();"outside"==c.shadowPosition&&(e.save(),k(e,b,f),e.globalCompositeOperation="destination-out",e.fillStyle="rgba(0,0,0,1);",e.fill(),e.restore())}e.save();k(e,b,f);c.fill&&(e.fillStyle=n(c.fillColor,c.fillOpacity),e.fill());c.stroke&&
(e.strokeStyle=n(c.strokeColor,c.strokeOpacity),e.lineWidth=c.strokeWidth,e.stroke());e.restore();c.fade&&a(d).css("opacity",0).animate({opacity:1},100)},t=function(d){d.getContext("2d").clearRect(0,0,d.width,d.height);a.fn.maphilite.inFocus&&a.fn.maphilite.mouseLeave&&(a.fn.maphilite.mouseLeave(a.fn.maphilite.inFocus),a.fn.maphilite.inFocus=null)},q=function(a){var b,f=a.getAttribute("coords").split(",");for(b=0;b<f.length;b++)f[b]=parseFloat(f[b]);return[a.getAttribute("shape").toLowerCase().substr(0,
4),f]},r=function(d,b){var f=a(d);return a.extend({},b,a.metadata?f.metadata():!1,f.data("maphilite"))},s={position:"absolute",left:0,top:0,padding:0,border:0};a.fn.maphilite=function(d){d=a.extend({},a.fn.maphilite.defaults,d);d.mouseEnter&&(a.fn.maphilite.mouseEnter=d.mouseEnter);d.mouseLeave&&(a.fn.maphilite.mouseLeave=d.mouseLeave);return this.each(function(){var b,f,c,e,g,h;c=a(this);a.fn.maphilite.img=this;b="undefined"!=typeof this.naturalWidth&&0===this.naturalWidth?!1:!0;if(!b)return window.setTimeout(function(){c.maphilite(d)},
200);f=a.extend({},d,a.metadata?c.metadata():!1,c.data("maphilite"));b=c.get(0).getAttribute("usemap");g=a('map[name="'+b.substr(1)+'"]');c.is('img,input[type="image"]')&&(b&&0<g.size())&&(c.hasClass("maphiliteed")&&(b=c.parent(),c.insertBefore(b),b.remove(),a(g).unbind(".maphilite").find("area[coords]").unbind(".maphilite")),b=a("<div></div>").css({display:"block",position:"relative",padding:0,width:this.width,height:this.height,overflow:"auto",background:'url("'+this.src+'")',"background-size":this.width,
"background-repeat":"no-repeat","background-position":"0px 0px"}),f.wrapClass&&(!0===f.wrapClass?b.addClass(a(this).attr("class")):b.addClass(f.wrapClass)),c.before(b).css("opacity",0).css(s).remove(),b.append(c),e=p(this),a.fn.maphilite.canvas=e,a(e).css(s),e.height=this.height,e.width=this.width,b=function(){var b,c;c=r(this,f);if(!c.neverOn&&!c.alwaysOn){a.fn.maphilite.img.width!=e.width&&(e=p(a.fn.maphilite.img),a.fn.maphilite.canvas=e);b=q(this);l(a.fn.maphilite.canvas,b[0],b[1],c,"highlighted");
if(b=a(this).attr("href"))a.fn.maphilite.mouseEnter&&(b=b.substr(1),a.fn.maphilite.mouseEnter(b)),a.fn.maphilite.inFocus=b;if(c.groupBy){var d=this;(/^[a-zA-Z][\-a-zA-Z]+$/.test(c.groupBy)?g.find("area["+c.groupBy+'="'+a(this).attr(c.groupBy)+'"]'):g.find(c.groupBy)).each(function(){if(this!=d){var a=r(this,f);if(!a.neverOn&&!a.alwaysOn){var b=q(this);l(e,b[0],b[1],a,"highlighted")}}})}}},a(g).bind("alwaysOn.maphilite",function(){h&&t(h);j||a(e).empty();a(g).find("area[coords]").each(function(){var b,
d;d=r(this,f);d.alwaysOn&&(!h&&j&&(h=p(c[0]),a(h).css(s),h.width=c[0].width,h.height=c[0].height,c.before(h)),d.fade=d.alwaysOnFade,b=q(this),j?l(h,b[0],b[1],d,""):l(e,b[0],b[1],d,""))})}),a(g).trigger("alwaysOn.maphilite").find("area[coords]").bind("mouseover.maphilite",b).bind("mouseout.maphilite",function(){t(e)}),c.before(e),c.addClass("maphiliteed"))})};a.fn.maphilite.defaults={fill:!0,fillColor:"000000",fillOpacity:0.2,stroke:!0,strokeColor:"ff0000",strokeOpacity:1,strokeWidth:1,fade:!0,alwaysOn:!1,
neverOn:!1,groupBy:!1,wrapClass:!0,mouseEnter:null,mouseLeave:null,shadow:!1,shadowX:0,shadowY:0,shadowRadius:6,shadowColor:"000000",shadowOpacity:0.8,shadowPosition:"outside",shadowFrom:!1}}else a.fn.maphilite=function(){return this}})(jQuery);
